# Generated by Django 5.0 on 2024-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('pc_logo', models.ImageField(blank=True, upload_to='upload')),
                ('mob_logo', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
    ]
