# Generated by Django 5.0 on 2024-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='table',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='product',
            name='table2',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
